#cloud-config
package_update: true
packages:
  - nfs-common
  - memcached
  - libmemcached-dev
  - libnuma-dev
  - build-essential
  - python3
  - python3-pip

mounts:
  - [ "10.10.1.1:/nfs_share", "/nfs_share", "nfs", "defaults", "0", "0" ]

write_files:
  - path: /etc/sysctl.d/90-rolex-hugepages.conf
    content: |
      vm.nr_hugepages=36000

runcmd:
  # Wait for mounting
  - while [ ! -f /nfs_share/ROLEX/script/installLibs.sh ]; do sleep 5; done

  - systemctl mask opensmd.service
  - /nfs_share/ROLEX/script/installLibs.sh
  - /nfs_share/ROLEX/script/installMLNX.sh

  - sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="/GRUB_CMDLINE_LINUX_DEFAULT="iommu=pt amd_iommu=off /' /etc/default/grub
  - update-grub

power_state:
  mode: reboot
  message: "Worker init finished, rebooting to apply MLNX and GRUB changes"
  condition: True
